name: Build forum-ui-dev docker image

on:
  push:
    branches: [ dev ]

  workflow_dispatch:

jobs:
  build_dev:
    name: Build forum-ui
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: vizlex/forum-ui-test
          dockerfile: ./Dockerfile
          tags: latest

  build_rest:
    name: Build forum-rest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: vizlex/forum-ui-test
          dockerfile: ./server/Dockerfile
          tags: rest
